### PR TITLE
Removed KafkaStreams.

### LINKED ISSUE #50: Kafka exception leave hydra in zombie mode
If there is single connection problem to the cassandra, then application will throws exception which kills application.
Example:
```
Caused by: org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:725)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:604)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1173)
	at org.apache.kafka.streams.processor.internals.StreamTask.commitOffsets(StreamTask.java:307)
	at org.apache.kafka.streams.processor.internals.StreamTask.access$000(StreamTask.java:49)
	at org.apache.kafka.streams.processor.internals.StreamTask$1.run(StreamTask.java:268)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:187)
	at org.apache.kafka.streams.processor.internals.StreamTask.commitImpl(StreamTask.java:259)
	at org.apache.kafka.streams.processor.internals.StreamTask.suspend(StreamTask.java:362)
	at org.apache.kafka.streams.processor.internals.StreamTask.suspend(StreamTask.java:346)
	at org.apache.kafka.streams.processor.internals.StreamThread$3.apply(StreamThread.java:1118)
	at org.apache.kafka.streams.processor.internals.StreamThread.performOnStreamTasks(StreamThread.java:1448)
	at org.apache.kafka.streams.processor.internals.StreamThread.suspendTasksAndState(StreamThread.java:1110)
	... 11 more
```

### PR DESCRIPTION
**Pull request by klangner**
Refactored test, so they don't need kafka mockups
Fixed #50

### CODE REVIEW

File: src/test/scala/carldata/hydra/DataProcessorTest.scala [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+class DataProcessorTest extends FlatSpec with Matchers {
+
+  val now: LocalDateTime = LocalDateTime.now
+  val code: String =
+    """
+      |def f(a: Number): Number = a + 1
+      |def main(xs: TimeSeries): TimeSeries = map(xs, f)
+    """.stripMargin
+
+  val computationSet1: Seq[RealTimeJob] = Seq(
```
Comment (wenta) [inline src/test/scala/carldata/hydra/DataProcessorTest.scala]: This value is not used . 
So _code_ is unneccesary too.

File: src/test/scala/carldata/hydra/DataProcessorTest.scala [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    AddRealTimeJob("calc1", code, Seq("c0"), "c-out", now, now.plusDays(5))
+  )
+
+  val inputSet1 = Seq(
```
Comment (wenta) [inline src/test/scala/carldata/hydra/DataProcessorTest.scala]: This value is not used.
