### PR TITLE
Fixed #56

### LINKED ISSUE #56: Handle cassandra timeout
> 2017-11-23 00:18:23.410 [hydra-d72e9a55-9bc5-49d1-8b58-468152954439-StreamThread-1] ERROR o.a.k.s.p.internals.StreamThread - stream-thread [hydra-d72e9a55-9bc5-49d1-8b58-468152954439-StreamThread-1] Streams application error during processing:
> java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
>         at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
>         at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
>         at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
>         at scala.concurrent.Await$.result(package.scala:142)
>         at carldata.hydra.BatchProcessor$.process(BatchProcessor.scala:26)
>         at carldata.hydra.RTCommandProcessor.process(RTCommandProcessor.scala:38)
>         at carldata.hydra.Main$.$anonfun$buildRealtimeStream$1(Main.scala:96)
>         at org.apache.kafka.streams.kstream.internals.KStreamFlatMapValues$KStreamFlatMapValuesProcessor.process(KStreamFlatMapValues.java:40)
>         at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:47)
>         at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:187)
>         at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:133)
>         at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:82)
>         at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
>         at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:189)
>         at org.apache.kafka.streams.processor.internals.StreamThread.processAndPunctuate(StreamThread.java:679)
>         at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:557)
>         at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:527)
> 2017-11-23 00:18:23.419 [hydra-d72e9a55-9bc5-49d1-8b58-468152954439-StreamThread-1] WARN  o.a.k.s.p.internals.StreamThread - stream-thread [hydra-d72e9a55-9bc5-49d1-8b58-468152954439-StreamThread-1] Unexpected state transition from RUNNING to DEAD.
> 2017-11-23 00:18:23.424 [hydra-d72e9a55-9bc5-49d1-8b58-468152954439-StreamThread-1] ERROR carldata.hydra.Main$ - Uncaught exception
> Futures timed out after [30 seconds]

### PR DESCRIPTION
**Pull request by wenta**

### CODE REVIEW

File: src/main/scala/carldata/hydra/BatchProcessor.scala [hunk 1]
```diff
@@ -23,22 +25,30 @@ object BatchProcessor {
...
-        resultTs.dataPoints
-          .map(x => DataRecord(job.outputChannelId, x._1, x._2))
-          .map(serialize)
-      case Left(err) =>
-        StatsD.increment("batch.errors.script")
-        Log.warn("Can't compile script:" + job.script)
-        Log.warn(err)
-        Seq()
+    try {
+      val inputTs = Await.result(Future.sequence(futures), 30.seconds)
```
Comment (klangner) [inline src/main/scala/carldata/hydra/BatchProcessor.scala]: I think it is better to use: 
Duration.Inf

here.
